name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run plus command tests
        run: |
          echo -e "1\n2\n3" | python3 scripts/plus.py | grep 6
          echo -e "10\n20\n30" | python3 scripts/plus.py | grep 60
